#- name: Perform apt-get update
#  apt:
#    update_cache: yes
#    cache_valid_time: 360
#  become: Yes

- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - git
    - xmlsec1
    - python3.5
    - python2.7
    - python-dev
    - python-setuptools
    - python-pip
    - python3-pip
    - nginx
    - mongodb
    - mongodb-clients
    - mongodb-server

- name: install python2 virtualenv
  pip:
    name: virtualenv
    executable: pip2

- name: install python3 virtualenv
  pip:
    name: virtualenv
    executable: pip3
