- name: Create project directory
  file: path={{ pyff_project_dir }} state=directory mode=0755

- name: fetch pyFF from {{ pyff_repo_url }}, version {{ pyff_repo_version }}
  git:
    repo: "{{ pyff_repo_url }}"
    dest: "{{ pyff_src_dir }}"
    version: "{{ pyff_repo_version }}"
    accept_hostkey: yes
    force: yes

- name: install pyFF from {{ pyff_src_dir }} to {{ pyff_env_dir }}
  pip:
    name: "{{ pyff_src_dir }}"
    virtualenv: "{{ pyff_env_dir }}"
    virtualenv_python: python2
    executable: pip2

- name: Create pyFF mdq configuration
  template: src=mdq.fd.j2
            dest="{{ pyff_env_dir }}/mdq.fd"
  become_method: sudo
  
- name: Create pyFF systemd service
  template: src=pyff.service.j2
            dest="{{ pyff_env_dir }}/pyff.service"
  become_method: sudo
  
- name: Create symlink to pyff.service in /etc/systemd/system
  file: src="{{ pyff_env_dir }}/pyff.service" dest=/etc/systemd/system/pyff.service state=link
  become_method: sudo

- name: restart pyff
  service: name=pyff state=restarted
  become_method: sudo
